name: BodyTracker
options:
  bundleIdPrefix: com.bodytracker
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  BodyTracker:
    type: application
    platform: macOS
    sources:
      - path: Sources/BodyTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bodytracker.BodyTracker
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        INFOPLIST_FILE: ""
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSMainNibFile: ""
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSCameraUsageDescription: "This app needs camera access to track body poses."

